/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;


import Config.connect;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;


/**
 *
 * @author LENOVO
 */
public class tabeltransaksi extends javax.swing.JFrame {

    /**
     * Creates new form tabelpelanggantransaksi
     */
    private String transaksi;
    public tabeltransaksi() {
        initComponents();
        tableTransaksi();
        tableDataBarang();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableTransaksi = new javax.swing.JTable();
        cetak = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        EDate = new javax.swing.JTextField();
        EjeFram = new javax.swing.JComboBox<>();
        EjenLens = new javax.swing.JComboBox<>();
        EharFram = new javax.swing.JLabel();
        EharLens = new javax.swing.JLabel();
        EHitung = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        ENama = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        Ebayar = new javax.swing.JTextField();
        Esisa = new javax.swing.JLabel();
        Eselesai = new javax.swing.JButton();
        EharTotal = new javax.swing.JLabel();
        Ekembalian = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dataBarang = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        home = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        keluar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1365, 823));
        setPreferredSize(new java.awt.Dimension(1391, 823));
        getContentPane().setLayout(null);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(1857, 13, 0, 0);

        jTabbedPane1.setBackground(new java.awt.Color(0, 153, 153));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setLayout(null);

        tableTransaksi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tableTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "Id Transaksi", "Date", "name", "Jenis Frame", "Harga Frame", "Jenis Lensa", "Harga Lensa"
            }
        ));
        tableTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableTransaksiMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableTransaksi);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(53, 75, 1184, 376);

        cetak.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        cetak.setText("Cetak");
        cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetakActionPerformed(evt);
            }
        });
        jPanel2.add(cetak);
        cetak.setBounds(1170, 520, 69, 25);

        jButton5.setForeground(new java.awt.Color(255, 0, 0));
        jButton5.setText("Hapus");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);
        jButton5.setBounds(1080, 520, 67, 25);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setText("Transaksi Toko Optik Amanah");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(465, 13, 317, 28);

        jTabbedPane1.addTab("Transaksi", jPanel2);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Form Edit Transaksi");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(613, 31, 156, 22);

        jPanel5.setBackground(new java.awt.Color(27, 114, 123));
        jPanel5.setLayout(null);

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));
        jPanel6.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Nama");
        jPanel6.add(jLabel11);
        jLabel11.setBounds(40, 80, 110, 22);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Jenis Frame");
        jPanel6.add(jLabel13);
        jLabel13.setBounds(42, 123, 110, 22);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Harga Frame");
        jPanel6.add(jLabel14);
        jLabel14.setBounds(42, 185, 100, 22);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Jenis Lensa");
        jPanel6.add(jLabel15);
        jLabel15.setBounds(42, 253, 107, 22);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("Harga Lensa");
        jPanel6.add(jLabel16);
        jLabel16.setBounds(42, 328, 115, 22);

        EDate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel6.add(EDate);
        EDate.setBounds(210, 30, 190, 28);

        EjeFram.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        EjeFram.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Calvin Klien", "Seiko", "Essilor", "Guess" }));
        EjeFram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EjeFramActionPerformed(evt);
            }
        });
        jPanel6.add(EjeFram);
        EjeFram.setBounds(209, 120, 226, 28);

        EjenLens.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        EjenLens.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trivex", "Photochromic", "Lensa", "Blue Ray" }));
        EjenLens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EjenLensActionPerformed(evt);
            }
        });
        jPanel6.add(EjenLens);
        EjenLens.setBounds(209, 250, 226, 28);

        EharFram.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        EharFram.setText("RP.");
        EharFram.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.add(EharFram);
        EharFram.setBounds(209, 183, 226, 26);

        EharLens.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        EharLens.setText("RP.");
        EharLens.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.add(EharLens);
        EharLens.setBounds(209, 326, 226, 26);

        EHitung.setText("Hitung");
        EHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EHitungActionPerformed(evt);
            }
        });
        jPanel6.add(EHitung);
        EHitung.setBounds(338, 383, 97, 25);

        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel6.add(jRadioButton1);
        jRadioButton1.setBounds(410, 30, 25, 25);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Date");
        jPanel6.add(jLabel12);
        jLabel12.setBounds(40, 30, 110, 22);

        ENama.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ENama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ENamaActionPerformed(evt);
            }
        });
        jPanel6.add(ENama);
        ENama.setBounds(210, 70, 190, 30);

        jPanel5.add(jPanel6);
        jPanel6.setBounds(0, 30, 486, 441);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("Harga Total");
        jPanel5.add(jLabel17);
        jLabel17.setBounds(577, 84, 105, 22);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setText("Bayar");
        jPanel5.add(jLabel18);
        jLabel18.setBounds(577, 137, 52, 22);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setText("Kembalian ");
        jPanel5.add(jLabel19);
        jLabel19.setBounds(580, 250, 101, 22);

        Ebayar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel5.add(Ebayar);
        Ebayar.setBounds(719, 134, 232, 28);

        Esisa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Esisa.setText("RP.");
        Esisa.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.add(Esisa);
        Esisa.setBounds(720, 250, 232, 26);

        Eselesai.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Eselesai.setText("Selesai");
        Eselesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EselesaiActionPerformed(evt);
            }
        });
        jPanel5.add(Eselesai);
        Eselesai.setBounds(830, 310, 117, 31);

        EharTotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        EharTotal.setText("RP.");
        EharTotal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.add(EharTotal);
        EharTotal.setBounds(719, 82, 232, 26);

        Ekembalian.setText("Kembalian");
        Ekembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EkembalianActionPerformed(evt);
            }
        });
        jPanel5.add(Ekembalian);
        Ekembalian.setBounds(829, 190, 120, 30);

        jPanel1.add(jPanel5);
        jPanel5.setBounds(120, 60, 1000, 500);

        jTabbedPane1.addTab("Edit Transaksi", jPanel1);

        jPanel4.setBackground(new java.awt.Color(0, 153, 153));

        dataBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nomor", "Jenis Frame", "Harga Frame", "Jenis Lensa", "Harga Lensa"
            }
        ));
        jScrollPane1.setViewportView(dataBarang);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(135, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        jTabbedPane1.addTab("Data Frame dan Lensa", jPanel4);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(10, 110, 1340, 650);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(1857, 13, 0, 0);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 0, 0);

        jPanel3.setBackground(new java.awt.Color(45, 183, 198));

        jLabel4.setBackground(new java.awt.Color(45, 183, 198));
        jLabel4.setFont(new java.awt.Font("Brush Script MT", 0, 36)); // NOI18N
        jLabel4.setText("Toko Optik Amanah");

        home.setText("Home");
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(51, 51, 255));
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Kelola");
        jLabel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        keluar.setText("Keluar");
        keluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                keluarMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/logoOptik.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 823, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(home)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addGap(28, 28, 28)
                        .addComponent(keluar)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(63, 63, 63))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(home)
                            .addComponent(jLabel10)
                            .addComponent(keluar)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(-8, 10, 1380, 96);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void keluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_keluarMouseClicked
        this.setVisible (false);
        new TokoOptik().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_keluarMouseClicked

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        this.setVisible (false);
        new TokoOptik().setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_homeMouseClicked

    private void cetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetakActionPerformed
        // TODO add your handling code here:
        try{
            InputStream is = TokoOptik.class.getResourceAsStream("/view/LaporanTransaksi.jasper");
            JasperPrint jsprint =JasperFillManager.fillReport(is,null, connect.configDB());
            JasperViewer.viewReport(jsprint, false);
            
            
        }catch(Exception e){
            System.out.println("error ="+ e.getMessage());
        }
    }//GEN-LAST:event_cetakActionPerformed

    private void tableTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableTransaksiMouseClicked
        // TODO add your handling code here:
        int baris = tableTransaksi.rowAtPoint(evt.getPoint());
        String Date = tableTransaksi.getValueAt(baris, 2).toString();
        EDate.setText(Date);
        String Nama = tableTransaksi.getValueAt(baris, 3).toString();
        ENama.setText(Nama);
        String JenisFrame = tableTransaksi.getValueAt(baris, 4).toString();
        EjeFram.setSelectedItem(JenisFrame);
        String hargaFrame = tableTransaksi.getValueAt(baris, 5).toString();
        EharFram.setText(hargaFrame);
        String jenislensa = tableTransaksi.getValueAt(baris, 6).toString();
        EjenLens.setSelectedItem(jenislensa);
        String hargalensa = tableTransaksi.getValueAt(baris, 7).toString();
        EharLens.setText(hargalensa);
        
        String id_transaksi = tableTransaksi.getValueAt(baris, 1).toString();
        transaksi = id_transaksi;
        
       
    }//GEN-LAST:event_tableTransaksiMouseClicked

    private void EjeFramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EjeFramActionPerformed
        // TODO add your handling code here:
        if (EjeFram.getSelectedItem().equals("Calvin Klien")) {
            EharFram.setText("400000");

        } else if (EjeFram.getSelectedItem().equals("Seiko")) {
            EharFram.setText("284000");

        } else if (EjeFram.getSelectedItem().equals("Essilor")) {
            EharFram.setText("560000");

        } else {
            EharFram.setText("1500000");
        }
    }//GEN-LAST:event_EjeFramActionPerformed

    private void EjenLensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EjenLensActionPerformed
        // TODO add your handling code here:
        if (EjenLens.getSelectedItem().equals("Trivex")) {
            EharLens.setText("800000");
        } else if (EjenLens.getSelectedItem().equals("Photochromic")) {
            EharLens.setText("256000");
        } else if (EjenLens.getSelectedItem().equals("lensa")) {
            EharLens.setText("480000");
        } else {
            EharLens.setText("500000");
        }
    }//GEN-LAST:event_EjenLensActionPerformed

    private void EHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EHitungActionPerformed
        // TODO add your handling code here:
        int hargaFrame = Integer.parseInt(EharFram.getText());
        int hargaLensa = Integer.parseInt(EharLens.getText());
        int hitung = hargaFrame + hargaLensa;

        EharTotal.setText(Integer.toString(hitung));
    }//GEN-LAST:event_EHitungActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        if (jRadioButton1.isSelected()) {
//            tanggal();
        }
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void ENamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ENamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ENamaActionPerformed

    private void EselesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EselesaiActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "UPDATE transaksi SET nama = '" + ENama.getText()
                    + "', jenisfram = '" + EjeFram.getSelectedItem()
                    + "', hargaFrame = '" + EharFram.getText()
                    + "', jenisLensa = '" + EjenLens.getSelectedItem()
                    + "', hargalensa = '" + EharLens.getText()
                    + "', total= '" + EharTotal.getText()
                    + "'" + "WHERE id_transaksi ="+transaksi;

            java.sql.Connection conn = (Connection) connect.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Transaksi berhasil di Update");
            struk();
        } catch (SQLException x) {
            JOptionPane.showMessageDialog(this, x.getMessage());
        }
        tableTransaksi();
        
        
    }//GEN-LAST:event_EselesaiActionPerformed

    private void EkembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EkembalianActionPerformed
        // TODO add your handling code here:
        int hargaTotal = Integer.parseInt(EharTotal.getText());
        int bayarP = Integer.parseInt(Ebayar.getText());
        int total = bayarP - hargaTotal;
        Esisa.setText(Integer.toString(total));
    }//GEN-LAST:event_EkembalianActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "delete from transaksi where id_transaksi='" + transaksi + "'";
            java.sql.Connection conn = (Connection) connect.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(this, "Berhasil di hapus");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
         tableTransaksi();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void tableDataBarang(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Nomor");
        model.addColumn("Jenis Frame");
        model.addColumn("Harga Frame");
        model.addColumn("Jenis Lensa");
        model.addColumn("Harga Lensa");
        //menampilkan data database kedalam tabel
        try {
            int no = 1;
            String sql = "select * from databarang";
            java.sql.Connection conn = (Connection) connect.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            while (res.next()) {
                model.addRow(new Object[]{no++,
                     res.getString(1),
                     res.getString(2),
                     res.getString(3),
                     res.getString(4)
                });
            }
            dataBarang.setModel(model);
        } catch (Exception e) {
            System.out.println("Error" + e.getMessage());
        }

    }
   
    
    private void tableTransaksi(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("NO");
        model.addColumn("ID Transaksi");
        model.addColumn("Tanggal");
        model.addColumn("Nama Pembeli");
        model.addColumn("Jenis frame");
        model.addColumn("Harga frame");
        model.addColumn("Jenis lensa");
        model.addColumn("Total");
        //menampilkan data database kedalam tabel
        try {
            int no = 1;
            String sql = "select * from transaksi";
            java.sql.Connection conn = (Connection) connect.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            while (res.next()) {
                model.addRow(new Object[]{no++,
                     res.getString(1),
                     res.getString(2),
                     res.getString(3),
                     res.getString(4),
                     res.getString(5),
                     res.getString(6),
                     res.getString(7)});
            }
            tableTransaksi.setModel(model);
        } catch (Exception e) {
            System.out.println("Error" + e.getMessage());
        }

    }
    private void struk(){
        try{
            InputStream is = TokoOptik.class.getResourceAsStream("/view/struk.jasper");
            JasperPrint jsprint =JasperFillManager.fillReport(is,null, connect.configDB());
            JasperViewer.viewReport(jsprint, false);
            
            
        }catch(Exception e){
            System.out.println("error ="+ e.getMessage());
        }
    }
   
     /* @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tabeltransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tabeltransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tabeltransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tabeltransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tabeltransaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EDate;
    private javax.swing.JButton EHitung;
    private javax.swing.JTextField ENama;
    private javax.swing.JTextField Ebayar;
    private javax.swing.JLabel EharFram;
    private javax.swing.JLabel EharLens;
    private javax.swing.JLabel EharTotal;
    private javax.swing.JComboBox<String> EjeFram;
    private javax.swing.JComboBox<String> EjenLens;
    private javax.swing.JButton Ekembalian;
    private javax.swing.JButton Eselesai;
    private javax.swing.JLabel Esisa;
    private javax.swing.JButton cetak;
    private javax.swing.JTable dataBarang;
    private javax.swing.JLabel home;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel keluar;
    private javax.swing.JTable tableTransaksi;
    // End of variables declaration//GEN-END:variables

}
