/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;
import javax.swing.JOptionPane;
import Config.connect;
import java.io.InputStream;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JFrame;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author LENOVO GAMING 3I
 */
public class TokoOptik extends javax.swing.JFrame {

    /**
     * Creates new form TokoOptik
     */
    public TokoOptik() {
        initComponents();
        setLocationRelativeTo(this);
//        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
//        kosong();
    }

    

    public void tanggal() {
        DateFormat tgl = new SimpleDateFormat("dd.MM.yyyy/hh:mm:ss");
        String htgl = tgl.format(Calendar.getInstance().getTime());
        tDate.setText(htgl);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tDate = new javax.swing.JTextField();
        jeFram = new javax.swing.JComboBox<>();
        jenLens = new javax.swing.JComboBox<>();
        harFram = new javax.swing.JLabel();
        harLens = new javax.swing.JLabel();
        Hitung = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        tNama = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        bayar = new javax.swing.JTextField();
        sisa = new javax.swing.JLabel();
        selesai = new javax.swing.JButton();
        harTotal = new javax.swing.JLabel();
        tBatal = new javax.swing.JButton();
        kembalian = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        kelola = new javax.swing.JLabel();
        home = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();

        jTabbedPane1.setBackground(new java.awt.Color(46, 162, 175));
        jTabbedPane1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1296, 950));
        getContentPane().setLayout(null);

        jPanel3.setBackground(new java.awt.Color(27, 114, 123));
        jPanel3.setLayout(null);

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Nama");
        jPanel5.add(jLabel10);
        jLabel10.setBounds(40, 80, 110, 22);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Jenis Frame");
        jPanel5.add(jLabel13);
        jLabel13.setBounds(42, 123, 110, 22);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Harga Frame");
        jPanel5.add(jLabel14);
        jLabel14.setBounds(42, 185, 100, 22);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Jenis Lensa");
        jPanel5.add(jLabel15);
        jLabel15.setBounds(42, 253, 107, 22);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("Harga Lensa");
        jPanel5.add(jLabel16);
        jLabel16.setBounds(42, 328, 115, 22);

        tDate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel5.add(tDate);
        tDate.setBounds(210, 30, 190, 28);

        jeFram.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jeFram.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Calvin Klien", "Seiko", "Essilor", "Guess" }));
        jeFram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jeFramActionPerformed(evt);
            }
        });
        jPanel5.add(jeFram);
        jeFram.setBounds(209, 120, 226, 28);

        jenLens.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jenLens.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trivex", "Photochromic", "Lensa", "Blue Ray" }));
        jenLens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenLensActionPerformed(evt);
            }
        });
        jPanel5.add(jenLens);
        jenLens.setBounds(209, 250, 226, 28);

        harFram.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        harFram.setText("RP.");
        harFram.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.add(harFram);
        harFram.setBounds(209, 183, 226, 26);

        harLens.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        harLens.setText("RP.");
        harLens.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.add(harLens);
        harLens.setBounds(209, 326, 226, 26);

        Hitung.setText("Hitung");
        Hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HitungActionPerformed(evt);
            }
        });
        jPanel5.add(Hitung);
        Hitung.setBounds(338, 383, 97, 25);

        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jRadioButton1);
        jRadioButton1.setBounds(410, 30, 25, 25);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Date");
        jPanel5.add(jLabel11);
        jLabel11.setBounds(50, 30, 110, 22);

        tNama.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNamaActionPerformed(evt);
            }
        });
        jPanel5.add(tNama);
        tNama.setBounds(210, 70, 190, 30);

        jPanel3.add(jPanel5);
        jPanel5.setBounds(0, 45, 486, 441);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("Harga Total");
        jPanel3.add(jLabel17);
        jLabel17.setBounds(577, 84, 105, 22);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setText("Bayar");
        jPanel3.add(jLabel18);
        jLabel18.setBounds(577, 137, 52, 22);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setText("Kembalian ");
        jPanel3.add(jLabel19);
        jLabel19.setBounds(580, 250, 101, 22);

        bayar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel3.add(bayar);
        bayar.setBounds(719, 134, 232, 28);

        sisa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sisa.setText("RP.");
        sisa.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(sisa);
        sisa.setBounds(720, 250, 232, 26);

        selesai.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        selesai.setText("Selesai");
        selesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selesaiActionPerformed(evt);
            }
        });
        jPanel3.add(selesai);
        selesai.setBounds(830, 310, 117, 31);

        harTotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        harTotal.setText("RP.");
        harTotal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(harTotal);
        harTotal.setBounds(719, 82, 232, 26);

        tBatal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tBatal.setText("Batal");
        tBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tBatalActionPerformed(evt);
            }
        });
        jPanel3.add(tBatal);
        tBatal.setBounds(720, 310, 103, 31);

        kembalian.setText("Kembalian");
        kembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembalianActionPerformed(evt);
            }
        });
        jPanel3.add(kembalian);
        kembalian.setBounds(829, 190, 120, 30);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(140, 170, 995, 544);

        jPanel1.setBackground(new java.awt.Color(45, 183, 198));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Brush Script MT", 1, 36)); // NOI18N
        jLabel3.setText("Toko Optik Amanah");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(960, 20, 321, 45);

        logout.setText("LogOut");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        jPanel1.add(logout);
        logout.setBounds(1210, 90, 40, 16);

        kelola.setText("Kelola");
        kelola.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kelolaMouseClicked(evt);
            }
        });
        jPanel1.add(kelola);
        kelola.setBounds(1120, 90, 50, 16);

        home.setBackground(new java.awt.Color(0, 0, 255));
        home.setText("Home");
        home.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(home);
        home.setBounds(1000, 90, 58, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/logoOptik.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 211, 130);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1300, 120);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/bg2.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1000, 950);

        jPanel6.setBackground(new java.awt.Color(45, 183, 198));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 830, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel6);
        jPanel6.setBounds(1000, 110, 300, 830);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_logoutMouseClicked

    private void HitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HitungActionPerformed
        // TODO add your handling code here:
        int hargaFrame = Integer.parseInt(harFram.getText());
        int hargaLensa = Integer.parseInt(harLens.getText());
        int hitung = hargaFrame + hargaLensa;

        harTotal.setText(Integer.toString(hitung));
    }//GEN-LAST:event_HitungActionPerformed

    private void jeFramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jeFramActionPerformed
        // TODO add your handling code here:
        if (jeFram.getSelectedItem().equals("Calvin Klien")) {
            harFram.setText("400000");

        } else if (jeFram.getSelectedItem().equals("Seiko")) {
            harFram.setText("284000");

        } else if (jeFram.getSelectedItem().equals("Essilor")) {
            harFram.setText("560000");

        } else {
            harFram.setText("1500000");
        }
    }//GEN-LAST:event_jeFramActionPerformed

    private void jenLensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenLensActionPerformed
        // TODO add your handling code here:
        if (jenLens.getSelectedItem().equals("Trivex")) {
            harLens.setText("800000");
        } else if (jenLens.getSelectedItem().equals("Photochromic")) {
            harLens.setText("256000");
        } else if (jenLens.getSelectedItem().equals("lensa")) {
            harLens.setText("480000");
        } else {
            harLens.setText("500000");
        }
    }//GEN-LAST:event_jenLensActionPerformed

    private void selesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selesaiActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "INSERT into transaksi (date,nama,jenisFram,hargaFrame,jenisLensa,hargaLensa,total) values('"
                    + tDate.getText()
                    + "','" + tNama.getText()
                    + "','" + jeFram.getSelectedItem()
                    + "','" + harFram.getText()
                    + "','" + jenLens.getSelectedItem()
                    + "','" + harLens.getText()
                    + "','" + harTotal.getText()
                    + "')";
            java.sql.Connection conn = (Connection) connect.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Terima kasih Atas kunjungan anda, semoga anda nyaman ya ");
            struk();
        } catch (SQLException x) {
            JOptionPane.showMessageDialog(this, x.getMessage());
        }
        kosong();

    }//GEN-LAST:event_selesaiActionPerformed

    private void tBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tBatalActionPerformed
        // TODO add your handling code here:
        kosong();
    }//GEN-LAST:event_tBatalActionPerformed

    private void kelolaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kelolaMouseClicked
        this.setVisible(false);
        new tabeltransaksi().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_kelolaMouseClicked

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        if (jRadioButton1.isSelected()) {
            tanggal();
        }
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void tNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNamaActionPerformed

    private void kembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembalianActionPerformed
        // TODO add your handling code here:
        int hargaTotal = Integer.parseInt(harTotal.getText());
        int bayarP = Integer.parseInt(bayar.getText());
        int total = bayarP - hargaTotal;
        sisa.setText(Integer.toString(total));
    }//GEN-LAST:event_kembalianActionPerformed

    private void kosong() {
        tDate.setText(null);
        tNama.setText(null);
        jeFram.setSelectedItem(this);
        harFram.setText(null);
        jenLens.setSelectedItem(this);
        harLens.setText(null);
        harTotal.setText(null);
        bayar.setText(null);
        kembalian.setText(null);

    }
    
    private void struk(){
        try{
            InputStream is = TokoOptik.class.getResourceAsStream("/view/struk.jasper");
            JasperPrint jsprint =JasperFillManager.fillReport(is,null, connect.configDB());
            JasperViewer.viewReport(jsprint, false);
            
            
        }catch(Exception e){
            System.out.println("error ="+ e.getMessage());
        }
    }
//    private void struk

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TokoOptik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TokoOptik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TokoOptik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TokoOptik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TokoOptik().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Hitung;
    private javax.swing.JTextField bayar;
    private javax.swing.JLabel harFram;
    private javax.swing.JLabel harLens;
    private javax.swing.JLabel harTotal;
    private javax.swing.JLabel home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<String> jeFram;
    private javax.swing.JComboBox<String> jenLens;
    private javax.swing.JLabel kelola;
    private javax.swing.JButton kembalian;
    private javax.swing.JLabel logout;
    private javax.swing.JButton selesai;
    private javax.swing.JLabel sisa;
    private javax.swing.JButton tBatal;
    private javax.swing.JTextField tDate;
    private javax.swing.JTextField tNama;
    // End of variables declaration//GEN-END:variables
}
